# .NET Desktop

# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildConfiguration: 'Release'
  buildId: "1$(Build.BuildId)"

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonarcloud'
    organization: 'moerwald-github'
    scannerMode: 'MSBuild'
    projectKey: 'moerwald_Exceptions'
    projectName: 'Exceptions'


# Install SonarScanner
#- script: |
#    dotnet tool install --global dotnet-sonarscanner
#  displayName: 'install sonarscanner'
# Run Sonar
- script: |
     dotnet sonarscanner begin /k:"moerwald_Exceptions" 
  displayName: 'sonarscanner begin'
    
# Compile   
- script: |
    cd src\Mwd.Exceptions.Solution
    dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: |
    cd src\Mwd.Exceptions.Solution
    dotnet pack --configuration $(buildConfiguration)
  displayName: 'dotnet pack $(buildConfiguration)'
  
# Run tests
- script: |
    echo $(Build.SourcesDirectory)
    cd src\Mwd.Exceptions.Solution
    mkdir $(Build.SourcesDirectory)\results
    dotnet test --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura  
    copy Mwd.Exceptions.Test\coverage.cobertura.xml $(Build.SourcesDirectory)\results
     dotnet tool install dotnet-reportgenerator-globaltool --tool-path . --version 4.0.0-rc4
    .\reportgenerator "-reports:$(Build.SourcesDirectory)\results\coverage.cobertura.xml" "-targetdir:$(Build.SourcesDirectory)\results" "-reporttypes:HTMLInline;HTMLChart"
  displayName: 'Unit testing' 
   
# End SonarScanner
- script: |
    dotnet sonarscanner end 
  displayName: 'sonarscanner end'

    
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
   
  
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
- task: PublishCodeCoverageResults@1
  inputs:
    summaryFileLocation: $(Build.SourcesDirectory)\results\coverage.cobertura.xml
    reportDirectory: $(Build.SourcesDirectory)\results
    codecoverageTool: cobertura
    
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    projects: src\Mwd.Exceptions.Solution\Mwd.Exceptions\Mwd.Exceptions.csproj
    publishWebProjects: false
    modifyOutputPath: true
    zipAfterPublish: true

- task: PublishBuildArtifacts@1

